#
####服务启动端口号
#server:
#  port: 8400
####服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.192.103:8080/eureka
#threadPool:
#  corePoolSize: 10
#  maxPoolSize: 20
#  queueCapacity: 16
#spring:
#  application:
#    name:  app-mayikt-pay
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    pool:
#      max-idle: 100
#      min-idle: 1
#      max-active: 1000
#      max-wait: -1
####数据库相关连接
#  datasource:
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/meite_member?autoReconnect=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-timeout: 30000
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 600000
#      pool-name: DatebookHikariCP
#      max-lifetime: 28740000
#      connection-test-query: SELECT 1
#  rabbitmq:
#    ####连接地址
#    host: 127.0.0.1
#    ####端口号
#    port: 5672
#    ####账号
#    username: guest
#    ####密码
#    password: guest
#    ### 地址
#    virtual-host: /
#    listener:
#      simple:
#        retry:
#          ####开启消费者（程序出现异常的情况下会）进行重试
#          enabled: true
#          ####最大重试次数
#          max-attempts: 5
#          ####重试间隔时间
#          initial-interval: 1000
#        ####开启手动ack
#        acknowledge-mode: manual
#        default-requeue-rejected: false
#
#
#
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.mayikt.pay.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#  configuration:
#    call-setters-on-nulls: true
#    map-underscore-to-camel-case: true
#    cache-enabled: false
######打印MyBatias日志
#logging:
#  level:
#  ### 开发环境使用DEBUG 生产环境info或者error
#   com.mayikt.member.mapper: DEBUG
