###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-zuul
  redis:
    host: 120.78.137.82
    port: 6379
#    password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_gateway?autoReconnect=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://192.168.170.129:8080/eureka


### 配置网关反向代理
zuul:
  routes:
    api-a:
     ### 以 /api-weixin/访问转发到会员服务
      path: /api-weixin/**
      serviceId: app-mayikt-weixin
    api-b:
        ### 以 /api-member/访问转发到订单服务
      path: /api-member/**
      serviceId: app-mayikt-member
    api-c:
        ### 以 /api-pay/访问转发到订单服务
      path: /api-pay/**
      serviceId: app-mayikt-pay
    api-d:
      ### 以 /api-pay/访问转发到订单服务
      path: /api-spike/**
      serviceId: app-mayikt-spike