#### 整合freemarker  spring.main.allow-bean-definition-overriding=true
spring:
    main:
      allow-bean-definition-overriding: true
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-mayikt-portal-pay-web
    redis:
      host: 127.0.0.1
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
      session:
        store-type: redis
      ###数据库相关连接
    datasource:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/meite_member?autoReconnect=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          connection-timeout: 30000
          minimum-idle: 5
          maximum-pool-size: 15
          auto-commit: true
          idle-timeout: 600000
          pool-name: DatebookHikariCP
          max-lifetime: 28740000
          connection-test-query: SELECT 1
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://192.168.192.103:8080/eureka
server:
  port: 8600

#xxl-sso:
#  excluded:
#    paths:
#xxl:
#  sso:
#    server: http://xxlssoserver.com:8080/xxl-sso-server
#    logout:
#      path: /logout
#    redis:
#      address: redis://127.0.0.1:6379
#
#
